### PR TITLE
add(qbit-port-forward): add container

### PR DESCRIPTION
**Pull request by kqmaverick**
**Description**
Add container for qbit-port-forward

⚒️ Fixes  # 

**⚙️ Type of change**

- [X] ⚙️ Feature/App addition
- [ ] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**📃 Notes:**

**✔️ Checklist:**

- [ ] ⚖️ My code follows the style guidelines of this project
- [ ] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic versioning

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🪞 I have opened a PR on [truecharts/containers](https://github.com/truecharts/containers) adding the container to TrueCharts mirror repo.
- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

### CODE REVIEW

**Comment by Ornias1993** [comment]
This seems like another "combine an application with VPN tools"-container, which we are quite clear on not going to add.
Simply put:
If you want VPN support added either:
A. Add a seperate VPN chart (which is likely not going to accessable by another chart)
B. Add/modify the addons in common

**Comment by kqmaverick** [comment]
I was looking at adding this as a sidecar to qbittorrent. It would pick up the gluetun port forward and configure qbittorrent with it.

**Comment by Ornias1993** [comment]
> I was looking at adding this as a sidecar to qbittorrent. It would pick up the gluetun port forward and configure qbittorrent with it. It is a script running on a cronjob.

I dont think we need this at all tbh, because I think we have all that info (the port number) already and can just inject that with Helm instead?

**Comment by kqmaverick** [comment]
Some providers assign a random port on each connection. This would be a solution for that.

**Comment by Ornias1993** [comment]
> Some providers assign a random port on each connection. This would be a solution for that.

Okey that's a fair point.
Feel free to implement a prototype PR!

**Pull request merged**
