### PR TITLE
automatic-music-downlaoder

### PR DESCRIPTION
**Pull request by stavros-k**

### CODE REVIEW

**Comment by stavros-k** [comment]
no fixed tag available, only latest

**Comment by Ornias1993** [comment]
Before i'm going to merge this you need to know that passing hadolint is NOT optional.
The same goes for librephotos, which is not getting released because you still have not fixed the same lint issues there as well (for using latest)

**Comment by stavros-k** [comment]
I'm not really sure what is causing to pick up this hadolint comment as tag..

**Comment by Ornias1993** [comment]
Afaik space after # and or linebreak type (linhx vs windows)

**Comment by Ornias1993** [comment]
Ahh no, my mistake.
I need to global ignore this.
Please remove the hadolint ignore again :)

**Comment by stavros-k** [comment]
> Ahh no, my mistake. I need to global ignore this. Please remove the hadolint ignore again :)

Done

**Pull request merged**
