### PR TITLE
mirror flexget

### PR DESCRIPTION
**Pull request by Sagit-chu**
add flexget

### CODE REVIEW

**Comment by stavros-k** [comment]
Please use a better source for this image.
This image has a total of 7 pulls only...

**Comment by Sagit-chu** [comment]
> Please use a better source for this image. This image has a total of 7 pulls only...

This is what I modified according to the image of madwind/flexget, and his image label is only latest

**Comment by stavros-k** [comment]
https://hub.docker.com/r/wiserain/flexget
This looks better, with updates. also it's on flexget's website as proposed.

Is there any difference between those images?

**Comment by Sagit-chu** [comment]
> https://hub.docker.com/r/wiserain/flexget This looks better, with updates. also it's on flexget's website as proposed.
> 
> Is there any difference between those images?

This image may be missing some dependencies and some plugins cannot be used

**Comment by stavros-k** [comment]
The image I mentioned seems to have an easy way to add packages and plugins.

**Pull request merged**
